### ISSUE TITLE
Error: modules[moduleId] is undefined

### ISSUE THREAD

**Issue by yuvadm** [borisirota/webworkify-webpack#10] opened 2016-06-16 19:51 UTC
I'm getting a client-sude error `modules[moduleId] is undefined` coming from https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L14 not exactly sure when this started, but it happened after I purged my `node_modules` directory.

Any idea what's going on?

**Comment by borisirota** [comment] 2016-06-21 18:52
Hmmm I guess its related to https://github.com/borisirota/webworkify-webpack/pull/7, which means that now the first comparison is based on string and not "address". Maybe the `moduleId` is `undefined`.

Can you show me a code snippet of how you call `webworkify-webpack` ?

**Comment by borisirota** [comment] 2016-06-21 18:54
@yuvadm Is version 1.0.6 working ok ?

**Comment by yuvadm** [comment] 2016-06-21 18:56
@borisirota I don't believe so

**Comment by extronics** [comment] 2016-06-22 10:40
I ran into the same issue in Firefox and minified versions in other browsers. #11 fixed this for me.

**Comment by jwarning** [comment] 2016-06-22 22:21
I've had a similar issue trying to build mapbox-gl-js stuff since version 1.1.0. It was fine previously in 1.0.6, however since updating I'm getting a similar `Cannot read property 'call' of undefined` error in the console.

**Comment by borisirota** [comment] 2016-06-23 13:53
Should be fixed in version `1.1.1` with #11 so I'm closing the issue. Feel free to reopen if you still encounter issues.

Thanks !

**Comment by michaelhue** [comment] 2016-07-10 21:00
> I've had a similar issue trying to build mapbox-gl-js stuff since version 1.1.0. It was fine previously in 1.0.6, however since updating I'm getting a similar Cannot read property 'call' of undefined error in the console.

Same here with `webworkify-webpack@1.1.1` and `mapbox-gl@0.20.1`.

**Comment by shotor** [comment] 2016-07-12 10:51
I have the same issue as well with `webworkify-webpack@1.1.1` and `mapbox-gl@0.20.1`

**Comment by yuvadm** [comment] 2016-07-12 11:39
@borisirota i think this calls for a reopen

**Comment by borisirota** [comment] 2016-07-12 17:35
@michaelhue @shotor @yuvadm how are you using this lib ? when are you getting this error ? in development with `eval` as `devtool` (if so it won't work, check the [first caveat](https://github.com/borisirota/webworkify-webpack#caveats)) or production with code minification ? are you passing anonymous function to `webworkify-webpack` or named one ?

I need to understand your workflow guys because I'm not able to reproduce it.

Thanks.

**Comment by michaelhue** [comment] 2016-07-12 19:36
@borisirota You are absolutely right and I apologize for my shitty _shrug report_. I dug a little deeper and found that the error is twofold and completely user related, of course.

This is the fix for all the other mapbox-gl and webpack users coming here:
1. Ensure that the `devtool` option in your `webpack.config.js` file is **not** set to any value containing `eval`, as stated in this project's README and above. When in doubt set it to `null` and try again.
2. Open the file `node_modules/mapbox-gl/js/source/worker.js` and change the following lines:
   
   -module.exports = function(self) {
   +module.exports = function MapboxGlWorker(self) {

Note: This is a quick and dirty fix, I'll open a pull request at [mapbox-gl](https://github.com/mapbox/mapbox-gl-js) and reference this issue.

---

Sorry for the trouble @borisirota, I've learnt my lesson today. Remember kids, reading READMEs saves lifes.

**Comment by michaelhue** [comment] 2016-07-12 20:13
A better short-term fix would be just using one of the packaged distribution files via `mapbox-gl/dist/mapbox-gl.js`. This will produce a warning but as my late grandma used to say: warnings are better than errors.

**Comment by borisirota** [comment] 2016-07-13 00:39
@michaelhue no worries. Thanks !

**Closed as completed by borisirota** 2016-07-13 00:39 UTC
