### ISSUE TITLE
Could not locate module error with 1.1.7 or Uncaught Cannot read property 'call' of undefined with 1.1.3

### ISSUE THREAD

**Issue by gazpachu** [borisirota/webworkify-webpack#18] opened 2016-08-15 12:02 UTC
When trying to make react-mapbox-gl work, I get different errors with different versions of webworkify:

1.1.7:
`Uncaught Error: webworkify-webpack: Could not locate module containing worker function! Make sure you aren't using eval sourcemaps and that you pass named functions to webworkify-webpack!`

1.1.3:
`Uncaught TypeError: Cannot read property 'call' of undefined`

**Comment by borisirota** [comment] 2016-08-15 12:22
I'm not using neither `react-map-gl` nor `mapbox-gl` but from what I understand this is the case:

`react-map-gl` uses `mapbox-gl` [v0.0.21](https://github.com/uber/react-map-gl/blob/master/package.json#L26).

This issue should have been fixed in `mapbox-gl` [v0.0.22](https://github.com/mapbox/mapbox-gl-js/pull/2887).

So you should ask `react-map-gl` to use `mapbox-gl v0.0.22`.

Hope it helps. Feel free to reopen if this isn't fix the problem.

**Comment by gazpachu** [comment] 2016-08-15 13:16
I've installed mapbox-gl v0.22.0 and the issue still there

**Comment by borisirota** [comment] 2016-08-15 13:23
Is it the same issue ?
`Uncaught Error: webworkify-webpack: Could not locate module containing worker function! Make sure you aren't using eval sourcemaps and that you pass named functions to webworkify-webpack!`

**Comment by gazpachu** [comment] 2016-08-15 13:25
Yes, same scenario as the one in my initial message.

**Comment by borisirota** [comment] 2016-08-15 13:39
@gazpachu which browser do you use ?

@austinhyde as I'm not using `mapbox-gl` (and not `react-map-gl`) maybe you can give us a hint here :)

Is `webworkify-webpack` works for you after [this PR](https://github.com/mapbox/mapbox-gl-js/pull/2887) (`mapbox-gl` v0.0.22) was merged ?

[This PR](https://github.com/borisirota/webworkify-webpack/pull/7) started all the mess of string comparisons. Not sure what to do. Maybe to add another mode to `webworkify-webpack` with the old behavior if the error is browser quirks with string comparisons ?

**Comment by gazpachu** [comment] 2016-08-15 13:41
@borisirota Chrome Version 52.0.2743.116 (64-bit)

**Comment by borisirota** [comment] 2016-08-15 13:50
@gazpachu just to be sure, you aren't using eval sourcemaps, right ?

**Comment by gazpachu** [comment] 2016-08-15 13:52
Hmmm, I'm using karma-sourcemap-loader. This is my karma.conf.js:

preprocessors: {
            // add webpack as preprocessor
            'src/tests/test_index.js': ['webpack', 'sourcemap']
        },

but if I remove all the karma stuff, it doesn't seem to fix it anyway.

**Comment by borisirota** [comment] 2016-08-15 14:10
@gazpachu as shown in the [second attachment](https://github.com/uber/react-map-gl/issues/110#issuecomment-239806529), you're using eval as sourcemap. This is what you see in the error message and this is the cause for the error. Currently, there is no option to use `webworkify-webpack` with `eval` sourcemap as noted at the [first caveat](https://github.com/borisirota/webworkify-webpack#caveats) so set one of the [non eval options](https://webpack.github.io/docs/configuration.html#devtool) and it should fix the issue (or use v1.0.6).

Feel free to reopen if this isn't fixes the problem.

**Closed as completed by borisirota** 2016-08-15 14:10 UTC

**Comment by borisirota** [comment] 2016-10-29 13:41
@gazpachu in the new v2 there is no limitation on the `devtool` options (eval can be used as well)
